services:
  - type: web
    name: alimentto-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    branch: main
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: "REPLACE_WITH_DATABASE_URL"

databases:
  - name: alimentto-db
    engine: mysql
    version: "8"
    plan: starter
    numInstances: 1
    region: oregon
