services:
  - type: web_service
    name: alimentto-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    branch: main
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alimentto-db
          property: connectionString
      - key: PORT
        value: "8000"

databases:
  - name: alimentto-db
    engine: mysql
    version: "8"
    plan: starter
    numInstances: 1
    region: oregon
